version: '3'
services:
  db:
    container_name: office_work_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  web:
    container_name: office_work_web
    build: .
    command: tail -f /dev/null    
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/office_work
    ports:
      - 3000:3000
    depends_on:
      - db
    entrypoint: ./entrypoint.sh
    stdin_open: true
    tty: true